language: php

matrix:
  include:
    - php: 5.4
      dist: trusty
    - php: 5.5
      dist: trusty
    - php: 5.6
    - php: 7.0
    - php: 7.1
    - php: 7.2
    - php: 7.3

sudo: false

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

install:
  - composer install --no-interaction --prefer-source

script:
  - ./vendor/bin/parallel-lint --exclude vendor .
  - ./vendor/bin/phpunit --configuration phpunit.xml tests/
  - ./var-dump-check src
