name: Run unit tests

on:
  pull_request:
  push:
  # Allow manually triggering the workflow.
  workflow_dispatch:

# Cancels all previous workflow runs for the same branch that have not yet completed.
concurrency:
  # The concurrency group contains the workflow name and the branch name.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Run tests on PHP ${{ matrix.php }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php:
          - '5.4'
          - '5.5'
          - '5.6'
          - '7.0'
          - '7.1'
          - '7.2'
          - '7.3'
          # PHP 7.4 is tested in coverage section

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          ini-values: zend.assertions=1, error_reporting=-1, display_errors=On
          coverage: none
          tools: cs2pr

      - name: Install Composer dependencies
        uses: ramsey/composer-install@v2

      - name: 'Linting code'
        run: ./vendor/bin/parallel-lint --exclude vendor . --exclude git . --checkstyle | cs2pr

      - name: 'Run unit tests'
        run: composer phpunit

      - name: 'Check var dump on own code'
        run: ./var-dump-check src

  coverage:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          ini-values: zend.assertions=1, error_reporting=-1, display_errors=On
          coverage: xdebug

      - name: Install Composer dependencies - normal
        uses: "ramsey/composer-install@v2"

      - name: Run the unit tests with code coverage
        run: composer coverage

      - name: Install Coveralls
        if: ${{ success() }}
        run: composer require php-coveralls/php-coveralls:"^2.5.2" --no-interaction

      - name: Upload coverage results to Coveralls
        if: ${{ success() }}
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: vendor/bin/php-coveralls -v -x build/logs/clover.xml
